apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web-pod
  ports:
    # This maps incoming traffic on port 80 to port 3000 where the containers are running on, as defined in the deployment.
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http