apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-pod
    spec:
      containers:
      - name: web
        image: kahunacohen/hello-k8s:latest
        
        # envFrom:
        #   - configMapRef:
        #       name: web-configmap
        ports:
        - containerPort: 3000
          protocol: TCP